language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"
  - "pypy3"

before_install:
  - sudo apt-get install redis-server
  - sudo service redis-server start
  - redis-server --version
  - which redis-server
  - /bin/sleep 10

install:
  - "pip install . --use-mirrors"
  - "pip install hiredis"

script: ./tests.py

env:
  matrix:
  - "REDIS_PORT=6379"
  - "START_REDIS_SERVER=True REDIS_PORT=0 REDIS_HOST=/tmp/asyncio"
